management:
  info:
    os:
      enabled: true
    java:
      enabled: true
  endpoint:
    configprops:
      show-values: always
    env:
      show-values: always
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8080
  forward-headers-strategy: native
spring:
  cloud:
    nacos:
      discovery:
        namespace: public
        password: nacos
        server-addr: 119.3.223.16:8848
        username: nacos
  application:
    name: admin-monitor
  boot:
    admin:
      ui:
        title: Admin Monitor
        brand: <img src="assets/img/boot.svg">
        login-icon: assets/img/boot.svg
        favicon: assets/img/boot.svg
        favicon-danger: assets/img/boot-danger.svg
        view-settings:
          - name: "about"
            enabled: true
  output:
    ansi:
      enabled: always
logging:
  pattern:
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
  file:
    name: var/log/spring-boot-application.log

